name: Admin
on:
  push:
    branches:
      - master
    paths:
      - packages/admin/**
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Build
        run: |
          yarn
          yarn build
          # Hasil buildnya di packages/admin/dist