name: Admin
on:
  push:
    branches:
      - master
    paths:
      - packages/admin/**
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          yarn
          yarn build:lib
          yarn build:admin --mode staging
          ls packages/admin/dist
          # Hasil buildnya di packages/admin/dist