name: Admin
on:
  push:
    branches:
      - master
    paths:
      - packages/admin/**
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-secret-access-key: bE7Val5wD4bphT0/06Z+SWNKhJzCDcrOFOVek0Xd
          aws-access-key-id: AKIAU4YKI3EGXLJO6AR4
          aws-region: ap-southeast-1
      - name: Build
        run: |
          yarn
          yarn build:lib
          yarn build:admin --mode staging
          ls packages/admin/dist
          aws s3 sync --delete packages/admin/dist s3://gkmd-frontend-deployment-demo/admin/staging/
          aws cloudfront create-invalidation --distribution-id E21P1QPKYKMMVO --paths "/*"