name: Admin
on:
  push:
    branches:
      - master
    paths:
      - packages/admin/**
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build
        env:
          DEPLOYMENT_WEB: admin
          DEPLOYMENT_ENV: staging
          DEPLOYMENT_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          DEPLOYMENT_DISTRIBUTION: ${{ secrets.CF_DISTRIBUTION_ADMIN_STAGING }}
        run: |
          sh deployment.sh
