name: Build
on:
  workflow_dispatch:
    inputs:
      web:
        type: choice
        description: Web
        options: 
          - admin
          - seller
          - buyer
      environment:
        type: choice
        description: Environment
        options:
          - demo
          - erp

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check
        run: |
          echo ${{ inputs.web }}
          echo ${{ inputs.environment }}