name: Build
on:
  workflow_dispatch:
    inputs:
      web:
        type: choice
        description: Web
        options: 
          - admin
          - seller
          - buyer
      environment:
        type: choice
        description: Environment
        options:
          - demo
          - erp

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Set Variables
        run: |
          echo "UPPER_WEB=$(echo "${{ inputs.web }}" | tr '[:lower:]' '[:upper:]')" >> $GITHUB_ENV
          echo "UPPER_ENVIRONMENT=$(echo "${{ inputs.environment }}" | tr '[:lower:]' '[:upper:]')" >> $GITHUB_ENV
      - name: Build
        env:
          DEPLOYMENT_WEB: ${{ inputs.web }}
          DEPLOYMENT_ENV: ${{ inputs.environment }}
          DEPLOYMENT_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          DEPLOYMENT_DISTRIBUTION: ${{ secrets[format('CF_DISTRIBUTION_{0}_{1}', env.UPPER_WEB, env.UPPER_ENVIRONMENT)] }}
        run: |
          echo $DEPLOYMENT_DISTRIBUTION
          