name: Build
on:
  workflow_dispatch:
    inputs:
      app:
        type: choice
        description: App type
        options: 
        - admin
        - seller
        - buyer
      environment:
        type: choice
        description: Environment
        options: 
        - production
        - staging
        - demo

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check
        run: |
          env