name: Seller
on:
  push:
    branches:
      - master
    paths:
      - packages/seller/**
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Build
        run: |
          cd packages/seller && yarn build
          # Hasil buildnya di packages/seller/dist